# Generated by Django 4.2.9 on 2024-09-15 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="paglia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specie", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file_name",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tags",
                    models.CharField(
                        default="adventure,foodie,travel,fitness,nature,fun,inspiration",
                        max_length=255,
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        default="adventure,food,health,art,entertainment,science,lifestyle",
                        max_length=255,
                    ),
                ),
                ("image_name", models.CharField(max_length=255)),
                (
                    "image_alt",
                    models.CharField(default="Default Alt Text", max_length=255),
                ),
                (
                    "image_caption",
                    models.CharField(default="Default Caption", max_length=255),
                ),
                ("image_link", models.URLField()),
                ("draft", models.BooleanField(default=True)),
            ],
        ),
    ]
