# Generated by Django 4.2.9 on 2024-07-24 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomFeature",
        ),
        migrations.RemoveField(
            model_name="post",
            name="text",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.CharField(
                default="adventure,food,health,art,entertainment,science,lifestyle",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_alt",
            field=models.CharField(default="Default Alt Text", max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="image_caption",
            field=models.CharField(default="Default Caption", max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(
                default="adventure,foodie,travel,fitness,nature,fun,inspiration",
                max_length=255,
            ),
        ),
    ]
