# Generated by Django 4.2.9 on 2024-09-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_piante_grasse"),
    ]

    operations = [
        migrations.CreateModel(
            name="piante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specie", models.CharField(max_length=255)),
                ("famiglia", models.CharField(max_length=255)),
            ],
        ),
    ]
