# Generated by Django 4.2.9 on 2024-08-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_api_for_wagtail", "0003_delete_customfeature"),
        ("blog", "0003_delete_customfeature_remove_post_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="nation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_api_for_wagtail.nation",
            ),
            preserve_default=False,
        ),
    ]
