# Generated by Django 4.2.9 on 2024-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_nation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file_name",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
