# Generated by Django 4.2.9 on 2024-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_camion"),
    ]

    operations = [
        migrations.CreateModel(
            name="birre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marche", models.CharField(max_length=255)),
            ],
        ),
    ]
