# Generated by Django 4.2.9 on 2024-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_birre"),
    ]

    operations = [
        migrations.CreateModel(
            name="bibite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="profumi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=255)),
            ],
        ),
    ]
