# Generated by Django 4.2.9 on 2024-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_citta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ringhiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipologia", models.CharField(max_length=255)),
                ("marca", models.CharField(max_length=255)),
            ],
        ),
    ]
