# Generated by Django 4.2.9 on 2024-12-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_ringhiere"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=255)),
                (
                    "image_alt",
                    models.CharField(default="Default Alt Text", max_length=255),
                ),
                (
                    "image_caption",
                    models.CharField(default="Default Caption", max_length=255),
                ),
                ("image_link", models.URLField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="blog.post",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="piantegrasse",
        ),
    ]
