# Generated by Django 4.2.9 on 2024-05-08 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_api_for_wagtail", "0002_customfeature"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomFeature",
        ),
    ]
